myapp/urls.py
from django.urls import path # type: ignore
from . import views


urlpatterns = [
    path('', views.hello),
    path('videos/', views.ListVideoView.as_view(), name='n_videos'),
    # path('videos/<int:pk>/', views.ListVideoView.as_view(), name='n_videos')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('api/', include('api_rest.urls')),
]

myapp/models.py
from django.db import models # type: ignore

# Create your models here.

class guia(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    acronimo = models.CharField(max_length=10, default='')
    date = models.DateField(auto_now=True)

    def __str__(self):
        return self.name

class video(models.Model):
    # Información del video
    video_name = models.CharField(max_length=70, null=False)
    old_name = models.CharField(max_length=70, null=False)
    extension = models.CharField(max_length=10, null=False)
    file_name = models.TextField(null=False)

    # Identificadores
    code = models.CharField(max_length=10, null=False) # Codigo Example: 8jd36, null=Falseh
    script = models.TextField(null=False)
    acronimo = models.CharField(max_length=10, null=True) # El acriónimo de la guía simpre mayusculas

    num_images = models.IntegerField(default=0) # Numero de imagenes que tiene el video

    fecha = models.TextField(default='')
    position = models.TextField(default='') # Posición horizontal o vertical del video


    def __str__(self):
        return self.video_name + ' | ' + self.code

myapp/views.py
from django.shortcuts import render # type: ignore
from .models import guia, video
from django.views.generic import ListView # type: ignore
# Create your views here.

def hello(request):

    return render(request, 'index.html')


class ListVideoView(ListView):
    model = video
    template_name = 'index.html'
    context_object_name = 'videos'

    def get(self, request):
        video_data = video.objects.values('id', 'tittle', 'total_items', 'before_tittle', 'id_guia__name')
        video_data_json = list(video_data)

        num_item = video.objects.all()
        num_item_json = list(num_item)
        # num_item.calculate_siguiente_registro()
        
        print(num_item_json)
        print("Hola")

        with open('static/textoLENAY.txt', 'w') as f:
            f.write('linea uno')
        print('Archivo creado')
        print('última linea de código')

        return render(request, 'index.html', {'videos': video_data_json})

myapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VIDEO - PROECESSOR</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/myicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">

    <link rel="stylesheet" href="{% static 'css/index/templates.css' %}">
    <link rel="stylesheet" href="{% static 'css/index/organisms.css' %}">
    <link rel="stylesheet" href="{% static 'css/index/molecules.css' %}">
    <link rel="stylesheet" href="{% static 'css/index/atoms.css' %}">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/11.2.0/styles/default.min.css">
</head>
<body class="template_body">
    <div class="template_cont style_RES_CONT">
        <aside>
            <section class="cont_viwer">
                <div class="organism_fileOutput">
                    <p>Video View</p>
                    <nav id="cont_video" class="cont_viewer">
                        <nav class="video" id="video_output" style="display: none;">
                            <!-- STUB - CAPTURE VIWER -->
                        </nav>
                        <div class="cont_select_video" id="open_video_cont">
                            <input type="file" id="video_file" name="archivo" accept=".mp4">
                            <label id="label_file" for="video_file">Arrastra el video aquí</label>
                        </div>
                    </nav>
                    <div class="molecule_buttonsVideo_cont">
                        <div class="controllers_btn">
                            <button id="btn_volume">
                                <img src="{% static 'img/volume.png' %}" alt="">
                            </button>
                            <button id="btn_next2">
                                <img src="{% static 'img/next2.png' %}" alt="">
                            </button>
                            <button id="btn_pause_play">
                                <img src="{% static 'img/pause_play.png' %}" alt="">
                            </button>
                            <button id="btn_next1">
                                <img src="{% static 'img/next1.png' %}" alt="">
                            </button>
                            <button id="btn_slow">
                                <img src="{% static 'img/slow.png' %}" alt="">
                            </button>
                            <button id="btn_clear">
                                <img src="{% static 'img/clear.png' %}" alt="">
                            </button>
                            <button id="btn_fast">
                                <img style="height: 80%;" src="{% static 'img/fast.png' %}" alt="">
                            </button>
                        </div>
                        <button id="move_before">
                            <img src="{% static 'img/move_before.png' %}" alt="">
                        </button>
                        <button id="move_after">
                            <img src="{% static 'img/move_after.png' %}" alt="">
                        </button>
                        <button id="btn_capture" >
                            <img src="{% static 'img/icon_capture.png' %}" alt="">
                        </button>
                        <button id="btn_expand" >
                            <img src="{% static 'img/expand.png' %}" alt="">
                        </button>
                    </div>
                </div>
                <div class="organism_code">
                    <div class="subtitle">
                        <p>Insertar Código</p>
                        <button id="copy_code"> <img src="{% static 'img/icon_copy.png' %}" alt=""> Copiar</button>
                        <select class="atom_comboboxStack" id="select_stack">
                            <option value="1">Stack 1</option>
                            <option value="2">Stack 2</option>
                            <option value="3">Stack 3</option>
                            <option value="4">Stack 4</option>
                        </select>
                        <div>
                            Total:
                            <input type="text" value="" name="" id="total_videos" disabled>
                        </div>
                    </div>
                    <code>
                        <div id="insert_code">
                            <!-- STUB - CODE INSERT -->
                        </div>
                    </code>
                </div>
                <div class="organism_code">
                    <div class="molecule_navbarFile">
                        <p class="organism_th_1 tittle_file">Titulo</p>
                        <p class="organism_th_2">IMG</p>
                        <p class="organism_th_3">Acción</p>
                    </div>
                    <div class="organism_listFile">
                        <table id="table_videos">
                            <!-- STUB - TABLE GENERATED -->
                        </table>
                    </div>
                </div>
            </section>
            <section>
                <div class="atoms_navSettings">
                    <p>Screen</p>
                </div>
                <div class="organism_firsSettings">
                    <nav style="height: 50px;" class="captura" id="captura_output">
                        <!-- STUB - VIDEO VIWER -->
                        <!-- <div style="width: 100%; height: 100%;background: black;"></div> -->
                    </nav>
                    <div class="molecule_buttonsVideo_cont">
                        <button id="charger_capture">
                            <img src="{% static 'img/add_imgIcon.png' %}" alt="">
                        </button>
                        <button id="btn_download">
                            <img src="{% static 'img/icon_download.png' %}" alt="">
                        </button>
                    </div>
                </div>
                <div class="atoms_navSettings">
                    <p>Settings</p>
                </div>
                <div class="organism_firsSettings">
                    <div class="espacio_uno">
                        <select id="seleccion_category" name="seleccion">
                            <option value="">Categorias</option>
                            <!-- STUB - SELECTOR DE GUIAS -->
                        </select>
                        <span>Acronimo: <input maxlength="2" id="id_acronime" type="text" value="" name="" disabled></span>
                        <span>Código: <input id="id_code" type="text" value="" name="" disabled></span>
                    </div>

                    <div class="espacio_dos">
                        <p>Posición del video:</p>
                        <div class="cont_radios">
                            <div class="myradio">
                                <label for="opcion1">Horizontal (H)</label>
                                <input type="radio" id="opcion1" name="opciones" value="pH" checked>
                            </div>
                            <div class="myradio">
                                <label for="opcion2">Vertical (V)</label>
                                <input type="radio" id="opcion2" name="opciones" value="pV">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="atoms_navSettings">
                    <p>Inputs</p>
                </div>
                <div class="organism_input">
                        <div class="cont_desq">
                            <p>titulo/Brebe Descripción</p>
                            <div class="cont_text">
                                <textarea id="id_title" name="tittle" rows="2" cols="50" maxlength="70"></textarea>
                                <span id="total_description">0/70</span>
                            </div>

                            <!-- VIOSUALIZACION DE IMAGEN DE VIDEO -->
                            <div class="cont_viewImg">
                                <div id="id_only_imgs">
                                </div>
                                <input type="file" id="image_file" name="archivo" accept=".jpg" hidden>
                                <label for="image_file"><img src="/static/img/add_imgIcon.png" alt=""></label>
                                <label id="deleted_images"><img src="/static/img/deleted.png" alt=""></label>

                                <!-- <button></button> -->
                            </div>
                            <div class="names_view" id="names_references">
                                <!-- STUB - NAMES VIEW OF VIDEO AND IMAGES -->
                            </div>
                            <input type="submit" id="id_submit" value="Subir Archivo">
                            <a class="atom_btnSnippet" href="/static/snippets/snpt_01.md">🧩 - [SNIPPET] - MANUAL</a>
                            <div class="organism_buttons">
                                <button id="id_clear" class="clear">LIMPIAR</button>
                            </div>
                        </div>
                </div>
            </section>
        </aside>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script type="module" src="{% static 'js/index.js' %}"></script>
</body>
</html>